---
title: "Lab 7 Assignment: Group 07"
author: "Anne Sofie Jokumsen (s244028), Sophia Cash (s225099), Norbert Bálint (s204668), Madeline Shah (s241901), Bedri Duraksoy (s233415)"
format:
  html:
    embed-resources: true
execute:
  warning: false
editor: visual
---

## **Loading**

The following loads the data set and the packages used throughout this code. It assumes that the packages loaded are already installed.

```{r}

library(tidyverse)
library(broom)

nba_dataset <- read_csv("data/_raw/nba_2017_nba_players_with_salary.csv")
```

## Analysis

### Modifying Data to PC Coordinates

```{r}
pca_fit_nba <- nba_dataset |> 
  select(where(is.numeric)) |>
  scale() |>
  prcomp() 
```

### Scatter of Fitted Data

```{r}
pca_fit |>
  augment(nba_dataset) %>% # add original dataset back in
  ggplot(aes(.fittedPC1, .fittedPC2, color = outcome)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(malignant = "#D55E00", benign = "#0072B2")
  ) +
  theme_half_open(12) + background_grid()
```

### Plotting of Rotation Matrix

```{r}
# define arrow style for plotting
arrow_style <- arrow(
  angle = 20, ends = "first", type = "closed", length = grid::unit(8, "pt")
)

# plot rotation matrix
pca_fit_nba |>
  tidy(matrix = "rotation") %>%
  pivot_wider(names_from = "PC", names_prefix = "PC", values_from = "value") |>
  ggplot(aes(PC1, PC2)) +
  geom_segment(xend = 0, yend = 0, arrow = arrow_style) +
  geom_text(
    aes(label = column),
    hjust = 1, nudge_x = -0.02, 
    color = "#904C2F"
  ) +
  xlim(-1.25, .5) + ylim(-.5, 1) +
  coord_fixed() + 
  theme_minimal_grid(12)
```

### Variance by PC plot

```{r}
pca_fit_nba |>
  tidy(matrix = "eigenvalues") %>%
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 0.8) +
  scale_x_continuous(breaks = 1:9) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  )
```
